In [47]:
import pandas as pnd;
import numpy as np;

In [48]:
dataset=pnd.read_csv('mail_data.csv');
X=dataset['Message'];
Y=dataset['Category'];

In [49]:
print(X.size);

5572


In [50]:
print(Y);

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object


In [51]:
print(dataset.isnull().sum());

Category    0
Message     0
dtype: int64


In [52]:

from sklearn.preprocessing import LabelEncoder#for Dependent variable
le=LabelEncoder();#to be used for binary categorical data only e.g true and false
Y=le.fit_transform(Y);
print(Y);
#we get spam=1,and ham=0;
# label spam mail as 0;  ham mail as 1;

#this will work as well.
#in loc first element select row and second elemnt is column.
# dataset.loc[dataset['Category'] == 'spam', 'Category'] = 1
# dataset.loc[dataset['Category'] == 'ham', 'Category'] = 0

[0 0 1 ... 0 0 0]


In [53]:
#split data
from sklearn.model_selection import train_test_split;
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=1,test_size=0.2);

In [97]:
from sklearn.feature_extraction.text import TfidfVectorizer;

vectorizer=TfidfVectorizer(min_df = 1, stop_words='english');
X_train=vectorizer.fit_transform(X_train);
X_test=vectorizer.transform(X_test);

AttributeError: 'csr_matrix' object has no attribute 'lower'

In [98]:
print(X_train);

  (0, 3321)	0.2638802854739516
  (0, 3789)	0.4750235197588447
  (0, 3822)	0.37729728742748087
  (0, 2719)	0.299459437576315
  (0, 5895)	0.415102954745324
  (0, 6695)	0.3616065178053154
  (0, 2353)	0.2545072203817634
  (0, 4346)	0.3238008504874723
  (1, 3365)	0.5510421389942982
  (1, 1858)	0.5163195438969705
  (1, 4343)	0.6555659308129219
  (2, 3185)	0.3663054742561573
  (2, 3025)	0.3502912545366897
  (2, 5672)	0.32606636481997364
  (2, 6597)	0.40097414833733686
  (2, 6215)	0.43979370278404856
  (2, 4267)	0.531599749449541
  (3, 6514)	0.16150638564730485
  (3, 1168)	0.20930686903969756
  (3, 1689)	0.25710735243209026
  (3, 2322)	0.2448089292310804
  (3, 3987)	0.27640333020388075
  (3, 4035)	0.2823414163958387
  (3, 6789)	0.1937220783869856
  (3, 1681)	0.22454159820679026
  :	:
  (4454, 1668)	0.3559334694518041
  (4454, 5420)	0.3559334694518041
  (4454, 2394)	0.3559334694518041
  (4454, 1504)	0.3559334694518041
  (4454, 1357)	0.3559334694518041
  (4455, 5515)	0.17320790500652875
  (4455,

In [65]:

# from sklearn.naive_bayes import GaussianNB;
# classifier=GaussianNB();
# classifier.fit(X_train.toarray(),Y_train);
# from sklearn.metrics import accuracy_score,confusion_matrix;
# y_pred=classifier.predict(X_test.toarray());
# pm=confusion_matrix(Y_test,y_pred);
# print(pm);
# acc=accuracy_score(Y_test,y_pred);
# print(acc);

[[856 112]
 [ 11 136]]
0.8896860986547085


In [99]:
from sklearn.linear_model import LogisticRegression;
classifier=LogisticRegression(random_state=0);
classifier.fit(X_train,Y_train);
from sklearn.metrics import accuracy_score,confusion_matrix;
y_pred=classifier.predict(X_test);
pm=confusion_matrix(Y_test,y_pred);
print(pm);
acc=accuracy_score(Y_test,y_pred);
print(acc);

[[967   1]
 [ 32 115]]
0.9704035874439462


In [69]:
import tensorflow as tl;

#Trying with ann .

In [85]:
ann=tl.keras.models.Sequential();

In [86]:
ann.add(tl.keras.layers.Dense(units=9, activation='relu'))

In [89]:
ann.add(tl.keras.layers.Dense(units=9, activation='relu'))

In [90]:
ann.add(tl.keras.layers.Dense(units=1, activation='sigmoid'))

In [91]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [92]:
ann.fit(X_train,Y_train,batch_size=32,epochs=120)

Epoch 1/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6489 - loss: 0.6583
Epoch 2/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8616 - loss: 0.4490
Epoch 3/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8721 - loss: 0.2797
Epoch 4/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8605 - loss: 0.2235
Epoch 5/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8721 - loss: 0.1733
Epoch 6/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8647 - loss: 0.1484
Epoch 7/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8714 - loss: 0.1165
Epoch 8/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9310 - loss: 0.1064
Epoch 9/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9992 - loss: 0.1015
Epoch 10/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9996 - loss: 0.0903
Epoch 11/120
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9995 - loss: 0.0836
Epoch 12/120
140/140 ━━━━━━━━━━━━━━━━━━━━

In [96]:
from sklearn.metrics import accuracy_score,confusion_matrix;
y_pred=classifier.predict(X_test);
pm=confusion_matrix(Y_test,y_pred);
print(pm);
acc=accuracy_score(Y_test,y_pred);
print(acc);

[[967   1]
 [ 32 115]]
0.9704035874439462
